### PR TITLE
Fix: open participation page accessibility issues (Axe)

### LINKED ISSUE #62: [a11y] Issue 4: Submit button has insufficient contrast (Participation Page)
**Description:**

The submit button on the participation page has insufficient color contrast. The measured contrast ratio is 3.26, which is below the WCAG 2 AA minimum contrast ratio of 4.5:1.  This makes the button difficult to see for users with low vision.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the submit button using a browser's developer tools or a color contrast analyzer.

**Expected Behavior:**

The submit button should have a contrast ratio of at least 4.5:1 with the background.

**Actual Behavior:**

The submit button has a contrast ratio of 3.26, failing WCAG 2 AA guidelines.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** button

### LINKED ISSUE #63: [a11y] Issue 5: Privacy and TOS anchor links have insufficient contrast (Participation Page)
**Description:**

The Privacy and Terms of Service (TOS) anchor links on the participation page have insufficient color contrast. The measured contrast ratio is 2.95, which is below the WCAG 2 AA minimum contrast ratio of 4.5:1.  This makes these links difficult to see for users with low vision.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the Privacy and TOS anchor links using a browser's developer tools or a color contrast analyzer.

**Expected Behavior:**

The anchor links should have a contrast ratio of at least 4.5:1 with the background.

**Actual Behavior:**

The anchor links have a contrast ratio of 2.95, failing WCAG 2 AA guidelines.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** anchor

### LINKED ISSUE #64: [a11y] Issue 6: Missing title element (Participation Page)
**Description:**

The participation page is missing a `<title>` element.  The `<title>` element is crucial for screen reader users and search engine optimization (SEO).  Without it, screen reader users have difficulty understanding the page's content, and the page's visibility in search results may be reduced.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the HTML `<head>` section.

**Expected Behavior:**

A `<title>` element containing a concise, descriptive title for the page should be present.

**Actual Behavior:**

The `<title>` element is missing.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** title

### LINKED ISSUE #65: [a11y] Issue 7: Incorrect ARIA role for form element (Participation Page)
**Description:**

The participation page uses an ARIA role of "form" on a `<form>` element, which is redundant and can cause accessibility issues. The `<form>` element already has an implicit "form" role.  Using unnecessary ARIA roles can interfere with assistive technologies.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the `<form>` element using a browser's developer tools.

**Expected Behavior:**

The `<form>` element should not have an explicit ARIA role="form" attribute.

**Actual Behavior:**

The `<form>` element has an unnecessary ARIA role="form" attribute.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** form

### LINKED ISSUE #66: [a11y] Issue 8: Missing main element/landmark (Participation Page)
**Description:**

Similar to Issue #4, the participation page lacks a `main` element/landmark and various other landmarks (`header`, `nav`, `footer`).  These elements are essential for defining page structure and improving accessibility for assistive technologies.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the HTML structure.

**Expected Behavior:**

Presence of `main`, `header`, `nav`, and `footer` elements for proper semantic structure.

**Actual Behavior:**

Missing landmark elements, hindering accessibility.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** header, nav, main, footer

### LINKED ISSUE #67: [a11y] Issue 9: Missing level-one heading (Participation Page)
**Description:**

The participation page does not contain a level-one heading (`<h1>`).  This heading is important for screen reader users to navigate directly to the main content of the page.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the page's heading structure.

**Expected Behavior:**

A `<h1>` element should be present to indicate the main content of the page.

**Actual Behavior:**

A `<h1>` element is missing.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** h1

### LINKED ISSUE #69: [a11y] Issue 11: Missing heading hierarchy (Participation Page)
**Description:**

The participation page lacks a clear hierarchy of headings, making it difficult for users of assistive technologies to navigate and understand the page structure.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Review the heading structure using a screen reader or browser's developer tools.

**Expected Behavior:**

A logical and consistent hierarchy of headings (`<h1>`, `<h2>`, `<h3>`, etc.) should be present.

**Actual Behavior:**

The heading hierarchy is inconsistent and lacks proper structure.

**Component/Area:** Participation page

**Source:** Other

**Affected Elements:** headings

### LINKED ISSUE #72: [a11y] Issue 14: Missing title element (Participation Page)
**Description:**

The participation page is missing a `<title>` element, hindering navigation and accessibility for screen reader users.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the page's `<head>` section.

**Expected Behavior:**

A non-empty `<title>` element should be present.

**Actual Behavior:**

The `<title>` element is missing or empty.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** title

### PR DESCRIPTION
**Pull request by thomassth**
Fix https://github.com/orgs/CivicTechTO/projects/4/views/1?filterQuery=parti&pane=issue&itemId=82264013

WAVE highlighted more items & would need more structural change, will do in another commit.

### CODE REVIEW

**Comment by patcon** [comment]
@thomassth i think may have intended to base this PR off of what is now called `edge`, instead of the current `edge-civictechto` (the prior `edge` branch accidentally had some extra commits from me, so I renamed it to be more clearly our branch, and locked the new edge to only sync with upstream. Hopefully this avoids future confusion

I don't think compdem will accept your PR upstream until you rebase, as there's some unrelated commits related to our storybook prep in there :)

**Comment by NewJerseyStyle** [comment]
About branch name, sorry I didn't state clearly in the documentation before.

## When you create a branch:
### If you are fixing a bug
Name the branch with `fix/issue-<issue number>-<key word of issue>` (e.g. `fix/issues-25-display-button`)
### If you are adding feature described in [issues](https://github.com/CivicTechTO/polis/issues)
Name the branch with `feature/<key word about feature>-issue-<issue number>` (e.g. `feature/a11y-module-issue-13`)
### If the branch does not associate to any issue
We will get confused

## Creating PR
Create pull request to our `edge` branch from your repository/branch with changelog (so we know what you did, then we can verify your changes and test the code for integration test) in case changelog is too trivial for you, leverage AIs to write it is also a good idea. 🙇 

### [More about development](https://github.com/CivicTechTO/polis/wiki/Development#get-started)

**Comment by NewJerseyStyle** [comment]
Assigned @patcon as reviewer, assuming @thomassth wants to help in patcon's branch

**Comment by thomassth** [comment]
I'm still confused which branch are we working on right now

**Comment by NewJerseyStyle** [comment]
Now I guess the `edge` branch we used to use has been renamed as `edge-civictechto` but all description in documents were not updated so everyone was confused.

**Comment by patcon** [comment]
Ah I'm sorry! that was my fault for changing it without checking for docs to update 😞 

As I was doing it, I was wishing we had a PR-based way to edit settings, so the setings change could be discussed like a clear code change. I've used this on other projects: https://github.com/repository-settings/app (repo config-as-code)

But respectfully, I think this situation (accidentally pushing extra commits upstream) is kinda unrelated to what I did, no? we can't submit PR feature branches to upstream that have been branched off our active (and _different_) `edge` branch (whether we call it `edge` or `edge-civictechto` or whatever). Yes, I tried to clean up our commits in `edge`, but i believe someone immediately pushed the old commits back onto it? and avoiding that situation is at the core of what we need to resolve about this in our workflow, i think? (If I'm misunderstanding, I apologize!)

Regardless, sorry for generating an extra layer of confusion around something that was already confusing...! Appreciate y'all!

**Comment by patcon** [comment]
For now:
1. I merged the remote tracking branch remote/civictechto/edge into our `edge-civictechto`
2. I merged `edge-civictechto` into this feature branch

So now this PR is clean again 🎉

File: client-participation/js/templates/link-TOS-partial.handlebars [hunk 1]
```diff
@@ -1,12 +1,13 @@
...
+{{! Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>. }}
```
Comment (patcon) [inline client-participation/js/templates/link-TOS-partial.handlebars]: nit: pls revert (will explain later)

```suggestion
{{!-- Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>. --}}
```

File: client-participation/js/templates/link-TOS-partial.handlebars [hunk 2]
```diff
@@ -1,12 +1,13 @@
...
   href="http://pol.is/tos"
   target="_blank"
   style="
   font-family: Georgia;
-  color: rgb(150,150,150);
+  color: rgb(87,87,87);
   font-size: 18px;
-  letter-spacing: 2px;">
+  letter-spacing: 2px;"
+>
```
Comment (patcon) [inline client-participation/js/templates/link-TOS-partial.handlebars]: nit: pls revert (will explain later)

```suggestion
  letter-spacing: 2px;">
```

File: client-participation/js/templates/link-TOS-partial.handlebars [hunk 3]
```diff
@@ -1,12 +1,13 @@
...
   {{s.TOS}}
-</a>
+</a>
```
Comment (patcon) [inline client-participation/js/templates/link-TOS-partial.handlebars:12]: nit: pls revert (will explain later)

File: client-participation/js/templates/link-privacy-partial.handlebars [hunk 4]
```diff
@@ -1,12 +1,13 @@
...
+{{! Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>. }}
```
Comment (patcon) [inline client-participation/js/templates/link-privacy-partial.handlebars]: nit: pls revert (will explain later)

```suggestion
{{!-- Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>. --}}
```

File: client-participation/js/templates/link-privacy-partial.handlebars [hunk 5]
```diff
@@ -1,12 +1,13 @@
...
   style="
   font-family: Georgia;
-  color: rgb(150,150,150);
+  color: rgb(87,87,87);
   font-size: 18px;
   letter-spacing: 2px;
   margin-inline-end: 5px;
-    ">{{s.privacy}}</a>
+    "
+>{{s.privacy}}</a>
```
Comment (patcon) [inline client-participation/js/templates/link-privacy-partial.handlebars:13]: nit: pls revert (will explain later)

File: client-participation/vis2/components/curate.js [hunk 6]
```diff
@@ -8,7 +8,7 @@ class Button extends React.Component {
     this.props.handleCurateButtonClick(this.props.identifier)
   }
 
-  render () {
+  render() {
```
Comment (patcon) [inline client-participation/vis2/components/curate.js:11]: nit: pls revert (will explain later)

File: client-participation/vis2/components/curate.js [hunk 7]
```diff
@@ -18,11 +18,11 @@ class Button extends React.Component {
         cursor: "pointer",
         padding: "6px 12px",
         fontWeight: (!_.isNull(this.props.selectedTidCuration) && this.props.selectedTidCuration === this.props.identifier) ? 700 : 500,
-        backgroundColor: (!_.isNull(this.props.selectedTidCuration) && this.props.selectedTidCuration === this.props.identifier) ? "#03a9f4" : "rgb(235,235,235)",
+        backgroundColor: (!_.isNull(this.props.selectedTidCuration) && this.props.selectedTidCuration === this.props.identifier) ? "#0076D1" : "rgb(235,235,235)",
         color: (!_.isNull(this.props.selectedTidCuration) && this.props.selectedTidCuration === this.props.identifier) ? "rgb(255,255,255)" : "rgb(100,100,100)",
         borderRadius: 4,
       }}
-      onClick={this.handleClick.bind(this)}>
+        onClick={this.handleClick.bind(this)}>
```
Comment (patcon) [inline client-participation/vis2/components/curate.js:25]: nit: pls revert (will explain later)

File: client-participation/vis2/components/curate.js [hunk 8]
```diff
@@ -40,7 +40,7 @@ class Curate extends React.Component {
   }
 
 
-  render () {
+  render() {
```
Comment (patcon) [inline client-participation/vis2/components/curate.js:43]: nit: pls revert (will explain later)

File: client-participation/vis2/components/curate.js [hunk 9]
```diff
@@ -49,7 +49,7 @@ class Curate extends React.Component {
         width: true ? "auto" : "100%",
 
       }}>
-        <div style={{marginRight: 20}}>
+        <div style={{ marginRight: 20 }}>
```
Comment (patcon) [inline client-participation/vis2/components/curate.js:52]: nit: pls revert (will explain later)

File: client-participation/vis2/components/curate.js [hunk 10]
```diff
@@ -63,11 +63,11 @@ class Curate extends React.Component {
...
-              marginRight: 10,
-              fontSize: 14,
-              fontFamily: "Georgia",
-              fontStyle: "italic"
-            }}>
+            marginRight: 10,
+            fontSize: 14,
+            fontFamily: "Georgia",
+            fontStyle: "italic"
+          }}>
```
Comment (patcon) [inline client-participation/vis2/components/curate.js:70]: nit: pls revert (will explain later)

File: client-participation/vis2/components/exploreTid.js [hunk 11]
```diff
@@ -6,7 +6,7 @@ import BarChart from "./barChart";
 const checkmark = "M1299 813l-422 422q-19 19-45 19t-45-19l-294-294q-19-19-19-45t19-45l102-102q19-19 45-19t45 19l147 147 275-275q19-19 45-19t45 19l102 102q19 19 19 45t-19 45zm141 83q0-148-73-273t-198-198-273-73-273 73-198 198-73 273 73 273 198 198 273 73 273-73 198-198 73-273zm224 0q0 209-103 385.5t-279.5 279.5-385.5 103-385.5-103-279.5-279.5-103-385.5 103-385.5 279.5-279.5 385.5-103 385.5 103 279.5 279.5 103 385.5z";
 const ban = "M1440 893q0-161-87-295l-754 753q137 89 297 89 111 0 211.5-43.5t173.5-116.5 116-174.5 43-212.5zm-999 299l755-754q-135-91-300-91-148 0-273 73t-198 199-73 274q0 162 89 299zm1223-299q0 157-61 300t-163.5 246-245 164-298.5 61-298.5-61-245-164-163.5-246-61-300 61-299.5 163.5-245.5 245-164 298.5-61 298.5 61 245 164 163.5 245.5 61 299.5z";
 
-const DataSentence = ({math, selectedTidCuration, selectedComment, repfulFor, Strings}) => {
+const DataSentence = ({ math, selectedTidCuration, selectedComment, repfulFor, Strings }) => {
```
Comment (patcon) [inline client-participation/vis2/components/exploreTid.js:9]: nit: pls revert (will explain later)

File: client-participation/vis2/components/exploreTid.js [hunk 12]
```diff
@@ -38,21 +38,21 @@ const DataSentence = ({math, selectedTidCuration, selectedComment, repfulFor, St
     s = s.replace("{{comment_id}}", tid);
 
     markup = (
-      <div style={{display: "flex"}}>
+      <div style={{ display: "flex" }}>
```
Comment (patcon) [inline client-participation/vis2/components/exploreTid.js:41]: nit: pls revert (will explain later)

File: client-participation/vis2/components/exploreTid.js [hunk 13]
```diff
@@ -38,21 +38,21 @@ const DataSentence = ({math, selectedTidCuration, selectedComment, repfulFor, St
...
-            fill: repfulForAgree ? globals.colors.agree : globals.colors.disagree
-          }} viewBox="0 0 1792 1792">
-          <path d={repfulForAgree ? checkmark : ban}/>
-          </svg>
+          display: "inline",
+          marginRight: 10,
+          fill: repfulForAgree ? globals.colors.agree : globals.colors.disagree
+        }} viewBox="0 0 1792 1792">
+          <path d={repfulForAgree ? checkmark : ban} />
+        </svg>
```
Comment (patcon) [inline client-participation/vis2/components/exploreTid.js:48]: nit: pls revert (will explain later)

File: client-participation/vis2/components/exploreTid.js [hunk 14]
```diff
@@ -38,21 +38,21 @@ const DataSentence = ({math, selectedTidCuration, selectedComment, repfulFor, St
...
-            fontWeight: 500,
-            maxWidth: 240,
-            color: "rgb(180,180,180)"
-          }}>
+          fontSize: 14,
+          fontFamily: "Helvetica",
+          fontWeight: 500,
+          maxWidth: 240,
+          color: "rgb(117,117,117)"
+        }}>
```
Comment (patcon) [inline client-participation/vis2/components/exploreTid.js:55]: nit: pls revert whitespace (will explain later)

```suggestion
            fontSize: 14,
            fontFamily: "Helvetica",
            fontWeight: 500,
            maxWidth: 240,
            color: "rgb(117,117,117)"
          }}>
```

File: client-participation/vis2/components/exploreTid.js [hunk 15]
```diff
@@ -69,21 +69,21 @@ const DataSentence = ({math, selectedTidCuration, selectedComment, repfulFor, St
     s = s.replace("{{comment_id}}", selectedComment.tid);
 
     markup = (
-      <div style={{display: "flex"}}>
+      <div style={{ display: "flex" }}>
```
Comment (patcon) [inline client-participation/vis2/components/exploreTid.js:72]: nit: pls revert (will explain later)

File: client-participation/vis2/components/exploreTid.js [hunk 16]
```diff
@@ -69,21 +69,21 @@ const DataSentence = ({math, selectedTidCuration, selectedComment, repfulFor, St
...
-            fill: repfulForAgree ? globals.colors.agree : globals.colors.disagree
-          }} viewBox="0 0 1792 1792">
-          <path d={repfulForAgree ? checkmark : ban}/>
-          </svg>
+          display: "inline",
+          marginRight: 10,
+          fill: repfulForAgree ? globals.colors.agree : globals.colors.disagree
+        }} viewBox="0 0 1792 1792">
+          <path d={repfulForAgree ? checkmark : ban} />
+        </svg>
```
Comment (patcon) [inline client-participation/vis2/components/exploreTid.js:79]: nit: pls revert (will explain later)

File: client-participation/vis2/components/exploreTid.js [hunk 17]
```diff
@@ -69,21 +69,21 @@ const DataSentence = ({math, selectedTidCuration, selectedComment, repfulFor, St
...
-            fontWeight: 500,
-            maxWidth: 240,
-            color: "rgb(180,180,180)"
-          }}>
+          fontSize: 14,
+          fontFamily: "Helvetica",
+          fontWeight: 500,
+          maxWidth: 240,
+          color: "rgb(117,117,117)"
+        }}>
```
Comment (patcon) [inline client-participation/vis2/components/exploreTid.js]: nit: pls revert (will explain later)
```suggestion
            fontSize: 14,
            fontFamily: "Helvetica",
            fontWeight: 500,
            maxWidth: 240,
            color: "rgb(117,117,117)"
          }}>
```

File: client-participation/vis2/components/exploreTid.js [hunk 18]
```diff
@@ -132,16 +132,16 @@ class ExploreTid extends React.Component {
...
+        onClick={this.handleAgree.bind(this)}>
+        <svg
+          style={{
+            marginRight: 3,
+            position: "relative",
+            top: 2,
+            display: "inline-block"
+          }} fill="rgb(200,0,0)" width="15" viewBox="0 0 1792 1792"><path d="M1299 813l-422 422q-19 19-45 19t-45-19l-294-294q-19-19-19-45t19-45l102-102q19-19 45-19t45 19l147 147 275-275q19-19 45-19t45 19l102 102q19 19 19 45t-19 45zm141 83q0-148-73-273t-198-198-273-73-273 73-198 198-73 273 73 273 198 198 273 73 273-73 198-198 73-273zm224 0q0 209-103 385.5t-279.5 279.5-385.5 103-385.5-103-279.5-279.5-103-385.5 103-385.5 279.5-279.5 385.5-103 385.5 103 279.5 279.5 103 385.5z" /></svg>
+        Agree
+      </button>);
```
Comment (patcon) [inline client-participation/vis2/components/exploreTid.js:144]: nit: pls revert

**Comment by patcon** [comment]
heh ok, i didn't go straight to the end, but the ideal contributor etiquette is to not let your editor make a bunch of noisy changes that are not actually what you are asking to get in, and make review as clean and small and simple as it can be for maintainers :)

`git add . -p` is really helpful to selectively add things to git staging, and leave out extraneous changes

I don't usually care so much about this myself, but when ballpointpenguin was asking about whitespace, this was def it. Ironically, because the codebase is so messy, clean PRs seem to be really appreciated and get merged faster. Maybe it's the cognitive overload of maintaining such a messy codebase 😉 

If you have a codestyle change or cleanup you want to get into the codebase, I'd suggest doing that in one go, and having a PR and separate review specifically for all those fixups. Fixing them up on the fly in unrelated PRs is often not considered as helpful as it might appear, esp on a project like polis where PRs need to be really clean and in-scope

Sorry for all the words, but consider it advice on FOSS contributing in general on larger/important projects <3

File: client-participation/js/templates/participation.handlebars [hunk 19]
```diff
@@ -431,13 +431,13 @@
 
 </span> {{!-- end no_vis toggle wrapper --}}
 
-
+</main> {{! END PARTICIPATION VIEW DIV }}
```
Comment (patcon) [inline client-participation/js/templates/participation.handlebars:434]: Can you clarify what's happening here? Was it malformed before, and you're fixing it? This might need an explicity explanation in your upstream PR as well :)

**Comment by patcon** [comment]
As a final comment, this flag is helpful: it show what a PR review would look like when ignoring whitespace changes:
https://github.com/CivicTechTO/polis/pull/32/files?w=1

Unless you're submitting a PR to deal with whitespace changes, your actual PR should look pretty much like that -- 20 lines or so of diff :)  The hundreds of lines of whitespace changes shouldn't be happening in a PR that claimed to be scoped to accessibility, and it will likely not get merged on principle (it might seem a little strict, but i believe most serious project would have the same expectation 😅 )

File: client-participation/js/templates/participation.handlebars (hunk 19 above)
Comment (thomassth) [reply client-participation/js/templates/participation.handlebars:434]: I'm separating `footer` from `main` to better match the standard.

No change in content otherwise.

**Comment by NewJerseyStyle** [comment]
So for now I am trying to understand what is the expected behavior of a developer:
* We will use `edge-civictechto` as the destination of all PRs and it will serve a role like `develop` branch in git flow?
    * Developer will create new branch from `edge-civictechto` make change and merge back to `edge-civictechto` branch
    * We will merge `edge` into `edge-civictechto` after `edge` received update from `compdemocracy/polis`
    * We test and update document on `edge-civictechto` before we merge `edge-civictechto` into `main` (`main` is always a tested stable release with related docs)
* And `edge` will only be used to track upstream from `compdemocracy/polis`?

> 💬 Verify my understanding @patcon 



And about what happened before from my side yesterday:
* I unlocked `edge` branch and I thought it's locking was an accident
* At least I did one merge on `edge` before I figured out `edge` branch is no longer THE `edge` branch
* I locked it again later after I figured out it is not the `edge` I am looking for

Sorry for the mess 🥲

**Comment by patcon** [comment]
No no it's my fault. I was absent this week (had a bad mental health week, and needed to step back). I'll process your message and respond in the issue specifically about branching to keep things on-topic here :)

**Comment by NewJerseyStyle** [comment]
We can see, and I am sure people are happy to offer assist for mental issues (hiking, walking, talking etc.) if we know how @patcon 

On the other hand, let me organize the events related to branches

1. One day patcon proposed that we should have a branch to keep track upstream, `edge` was proposed to do the job
2. And I proposed that we should use dev branch to merge all PRs before merge to main, `dev` was proposed to do the job
3. Some members told me `edge` should be where we keep the latest development
4. We (patcon wasn't there) agreed to use `edge` to track the latest development of all sources (from `compdemocracy/polis` and from PRs of our member) to keep things easy to manage
5. `dev` is merged into `edge`
6. `edge` is merged into `main`
7. all PRs merge to `edge`
8. `edge` is renamed to `edge-civictechto`
9. We are confused
10. Here, now, this thread. It seems we had different expectation about what `edge` should be. So can you review and verify my understanding mentioned in [above comment](https://github.com/CivicTechTO/polis/pull/32#issuecomment-2422879601)? 🙏 thanks

**Comment by patcon** [comment]
For others: I responded back in https://github.com/CivicTechTO/polis/issues/35

**Comment by patcon** [comment]
FYI, when I tried to merge yesterday to made this PR cleaner, the upstream PR got messier: https://github.com/compdemocracy/polis/pull/1821 (I don't think we can do PRs to both with one branch in our current flow)

**Comment by NewJerseyStyle** [comment]
I am not sure what do you mean by messier, to me the issue would be github action script, everything else doesn't kill anyone so they can be resolved easily somehow

**Comment by NewJerseyStyle** [comment]
After fixing branching issues, E2E test for the merge of this PR reported failure. I created another issue for it: https://github.com/CivicTechTO/polis/issues/39

**Comment by Zen-cronic** [comment]
> heh ok, i didn't go straight to the end, but the ideal contributor etiquette is to not let your editor make a bunch of noisy changes that are not actually what you are asking to get in, and make review as clean and small and simple as it can be for maintainers :)
> 
> ...
> If you have a codestyle change or cleanup you want to get into the codebase, I'd suggest doing that in one go, and having a PR and separate review specifically for all those fixups. Fixing them up on the fly in unrelated PRs is often not considered as helpful as it might appear, esp on a project like polis where PRs need to be really clean and in-scope
> 

Agree, we appreciate your effort and contribution @thomassth, but clean PRs get reviewed and merged relatively faster in FOSS! also it's easier to spot actual code changes and bugs that way.

File: client-participation/js/templates/participation.handlebars [hunk 20]
```diff
@@ -168,7 +168,7 @@
 
     {{#unless no_topic}}
     {{#ifDefined topic}}
-      <h2
+      <h1
```
Comment (Zen-cronic) [inline client-participation/js/templates/participation.handlebars:171]: this change from `h2` to `h1` is what's probably causing the `client-participation/embeds.cy.js` fail as mentioned in #39. B/c in the e2e test we're checking for [h2](https://github.com/CivicTechTO/polis/blob/835c992922e427fca34c3f70c8370f3c9dc03135/e2e/cypress/e2e/client-participation/embeds.cy.js#L44). Access the following artifact [here](https://github.com/CivicTechTO/polis/actions/runs/11410788293/artifacts/2076102587). 

Embedded Conversations -- default embed -- renders a default embed (failed)

File: client-participation/js/templates/participation.handlebars [hunk 21]
```diff
@@ -189,7 +189,7 @@
          left: 6px;
         ">closed</span>
```
Comment (Zen-cronic) [inline client-participation/js/templates/participation.handlebars:190]: b/c `closed` is not wrapped inside an `h1`, the [assertion](https://github.com/CivicTechTO/polis/blob/835c992922e427fca34c3f70c8370f3c9dc03135/e2e/cypress/e2e/client-admin/conversation.cy.js#L90) fails. 
Artifact:
Conversation Configure -- Closing a Conversation -- responds properly to being closed (failed)

**Comment by thomassth** [comment]
I was gonna rebase & clean it up the linting after work, but it got merged already!

Since this is merged, I'll reuse my branch to fix up the upstream PR (just realized I didn't open it in my own account 🙈)

imo we should have a linting default, but it's not a must. And we do that, we probably should do a cleanup in a separate styling PR before enforcing such things.

**Comment by NewJerseyStyle** [comment]
I see. Sorry to merge it too soon after fixing branching problem.

And the Lint and other checks defined in GitHub Action was not triggered on the new branch name, I am fixing them
